# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - cpassignmenttwo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ASP-app
          path: '/published/**'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ASP-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cpassignmenttwo'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C01D60553C3F4B17870F9738A8A4D63C }}
          package: .

        - name: Build, Test, and Publish NuGet
          # You may pin to the exact commit or the version.
          # uses: wahinekai/actions-publish-nuget@0868d8edc7f82a9cb3d216164bf6aa9cbf746498
          uses: wahinekai/actions-publish-nuget@v3.0.1
          with:
            # NuGet Feed to publish to, defaults to https://{{ github.repository_owner }}/index.json
            nuget-feed-url: # optional, default is https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
            # Name of NuGet feed, defaults to github
            nuget-feed-name: # optional, default is github
            # Build configuration to use, defaults to Release
            config: # optional, default is Release
            # Version for this package
            version: 
            # Path to the project to package. Used in dotnet pack
            project-path: 
            # Path to the solution to restore, test, and build. Used indotnet restore, build, and test.
            solution-path: 
            # Password for NuGet Feed authentication & api key for pushing.
            nuget-feed-password: 
            # Username for NuGet Feed authentication. Defaults to {{ github.repository_owner }}.
            nuget-feed-user: # optional, default is ${{ github.repository_owner }}
            # Path for outputs to be published to. Defaults to {{ github.workspace }}/out
            output-path: # optional, default is ${{ github.workspace }}/out
